# Generated by Django 5.1.5 on 2025-02-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_per_price', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_total_purchase_price', models.IntegerField(blank=True, null=True)),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.product')),
            ],
        ),
    ]
